# Clean & universal starship prompt

format = """
$directory$git_branch$git_status$python$character
"""

[directory]
style = "bold blue"

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "bold purple"

[python]
symbol = "ğŸ "
style = "bold yellow"
format = "[$symbol$version]($style)"
